### ISSUE TITLE
Update to current keystone structure

### ISSUE THREAD

**Issue by 37eex9** [keystone-enclave/keyedge#12]
Hey,
I'm new to keystone and wonder if there is any motivation of updating this repository to the current (file) structure of the keystone-enclave/keystone. I think, since the keystone main repository holds all the other projects, like sm and sdk, the structure changed and now uses more CMakeLists than build scripts.

Trying to build a test eapp I got as far as running `vault.sh` but I cannot find the correct build script pointing to the eyrie runtime.

Maybe there is a way to make this run with the most recent keystone repo, I would not like to use an outdated keystone.

**Comment by dkohlbre** [comment]
Hi,
Unfortunately this tool is not supported at all any more. We should have deprecated this repository a few years back.
Edge calls are manually generated right now. (If we want automatic generation we probably should write a new tool, rather than update this one.)

Please feel free to use issues on the main Keystone repo if you run into problems with any edgecall stuff!
